# Generated by Django 4.2.13 on 2024-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="bonus",
            new_name="bonus_rate",
        ),
        migrations.RemoveField(
            model_name="client",
            name="addresses",
        ),
        migrations.RemoveField(
            model_name="client",
            name="contact_detail",
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_method",
            field=models.CharField(
                choices=[
                    ("line", "Line"),
                    ("facebook", "Facebook Messenger"),
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
